#!/usr/bin/env bash

DIST="./build/default"
APP_ID="$1"

if [ -z "$APP_ID" ]; then
	echo -e "\n\tUsage:\t$0 <appengine-app-id>\n" >&2
	exit 1
fi

# Build it.
echo "Building $APP_ID..."
polymer build

echo "Deploying $APP_ID..."
gcloud app deploy $DIST/app.yaml --project $APP_ID --promote --version 2
